chat_window.api.collector:
  path: '/api/chat/customer'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\chat_window\src\Controller\ChatWidowController::startChat'
  requirements:
    _permission: ['can_start_chat', 'can_manage_chat_support', 'can_access_chat_panel']

chat_window.support.panel:
  path: '/chat/panel'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\chat_window\src\Controller\ChatWidowController::chatSupportPanel'
  requirements:
    _permission: ['can_manage_chat_support', 'can_access_chat_panel']

chat_window.support.panel.agent.form:
  path: '/chat/panel/agent/register'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\chat_window\src\Controller\ChatWidowController::chatSupportRegister'
  requirements:
    _permission: ['can_manage_chat_support']