mobile_app.manifest:
  path: '/app.webmanifest'
  methods: ['GET']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::manifest'
  requirements:
    _permission: ['user', 'moderator', 'admin', 'super_admin', 'guest']

mobile_app.home:
  path: '/mobile/home'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::home'
  requirements:
    _permission: ['user', 'moderator', 'admin', 'super_admin', 'guest']

mobile_app.profile:
  path: '/mobile/profile'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::profile'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.search:
  path: '/mobile/search'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::search'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.settings:
  path: '/mobile/settings'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::settings'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.profile.edit:
  path: '/mobile/profile/edit'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::profileEdit'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.profile.share:
  path: '/mobile/profile/share'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::profileShare'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.user.login:
  path: '/mobile/user/login'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::login'
  requirements:
    _permission: ['guest']

mobile_app.user.register:
  path: '/mobile/user/register'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::register'
  requirements:
    _permission: ['guest']

mobile_app.user.forgot_password:
  path: '/mobile/user/forgot-password'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::forgotPassword'
  requirements:
    _permission: ['guest']

mobile_app.settings.storage:
  path: '/mobile/settings/storage'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::storage'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.about:
  path: '/mobile/about'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::about'
  requirements:
    _permission: ['user', 'moderator', 'admin', 'super_admin', 'guest']

mobile_app.user.logout:
  path: '/mobile/logout'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::logout'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.settings.delete_account:
  path: '/mobile/settings/delete-account'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::deleteAccount'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.settings.password:
  path: '/mobile/settings/password'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::password'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.settings.sessions:
  path: '/mobile/settings/sessions'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::sessions'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.settings.2fa:
  path: '/mobile/settings/2fa'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::twoFactor'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.user.verify_email:
  path: '/mobile/settings/verify-email'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::verifyEmail'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.settings.timezone:
  path: '/mobile/settings/timezone'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::timezone'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']

mobile_app.settings.save:
  path: '/mobile/settings/save'
  methods: ['GET', 'POST']
  defaults:
    _controller: 'Simp\Pindrop\Modules\mobile_app\src\Controller\ManifestController::save'
  requirements:
    _permission: ['user', 'moderator', 'super_admin', 'admin']