push_notification.token:
  path: '/push/notifiction/vapid/token'
  methods: ['GET']
  defaults:
    _controller: 'Simp\Pindrop\Modules\push_notification\src\Controller\PushNotificationController::tokenGenerator'
  requirements:
    _permission: ['can_manage_own_profile', 'can_view_public_content', 'can_access_admin_panel', 'can_manage_push_notifications']

push_notification.user.setting.save:
  path: '/push/notifiction/settings/user'
  methods: ['PUT', 'POST', 'GET']
  defaults:
    _controller: 'Simp\Pindrop\Modules\push_notification\src\Controller\PushNotificationController::saveEnabledBrowser'
  requirements:
    _permission: ['can_manage_own_profile', 'can_view_public_content', 'can_access_admin_panel', 'can_manage_push_notifications']

push_notification.settings:
  path: '/push/notifiction/settings/configurations'
  methods: ['GET']
  defaults:
    _controller: 'Simp\Pindrop\Modules\push_notification\src\Controller\PushNotificationController::collectConfiguration'
  requirements:
    _permission: ['can_manage_own_profile', 'can_view_public_content', 'can_access_admin_panel', 'can_manage_push_notifications']

push_notification.testing:
  path: '/push/notifiction/testing'
  methods: ['GET']
  defaults:
    _controller: 'Simp\Pindrop\Modules\push_notification\src\Controller\PushNotificationController::testing'
  requirements:
    _permission: ['can_administer_settings', 'can_manage_push_notifications']
